version: '3'

services:

  proxy:
    build: 
      context: "./Nginx"
      dockerfile: Dockerfile
    container_name: nginx
    tty: true # -it
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on:
      - app
    

  app: 
    build: 
      context: "./Node"
      dockerfile: Dockerfile
    networks:
      - nodenet
    tty: true # -it
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./Node:/usr/src/app:rw
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always # if down always auto restart
    tty: true # -it
    volumes:
      - .docker/.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=nodeuser
      - MYSQL_ROOT_PASSWORD=nodeuser
    ports:
      - '3306:3306'
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge